### ISSUE TITLE
Splitted locales for lazy loading purpose

### ISSUE THREAD

**Issue by nelsieborja** [amsul/react-translated#6]
This is by far the simplest and most straight forward library out there and bec of that I really want to use it for our next big project. But one thing that is missing which is not explained in the repo is this. Is it possible to split locales into separate files and then later load them on demand?

**Comment by amsul** [comment]
@nelsieborja I'm glad you think so 🙏 

The purpose of this package is to be a low-level library that puts no restrictions on how you load or split your locales. It assumes you've handled all that (since there are so many ways to do so).

That being said, since it's so low-level, you _**can**_ do exactly what you want to in several ways – it just hasn't been documented yet.

One way is you could do something like this:

```jsx
// translations/en.js
export default {
  'Hello, {firstName}': 'Hello, {firstName}',
}

// translations/fr.js
export default {
  'Hello, {firstName}': 'Salut {firstName}',
}

// Components
class App extends Component {
  state = {
    hasLoadedLocale: false,
    language: 'fr',
    translation: {},
  }
  componentWillMount() {
    loadLocale(this.state.language).then(data => {
      this.setState({
        hasLoadedLocale: true,
        translation: addLocale({
          locale: this.state.language,
          data,
          translation: this.state.translation,
        }),
      })
    })
  }
  render() {
    if (!this.state.hasLoadedLocale) {
      return <Loader />
    }
    return (
      <Provider
        language={this.state.language}
        translation={this.state.translation}
      >
        <Translate
          data={{ firstName: 'nelsieborja' }}
          text='Hello, {firstName}'
        />
      </Provider>
    )
  }
}

const addLocale = ({ locale, data, translation }) => {
  const keys = Object.keys(data)
  translation = { ...translation }
  keys.forEach(key => {
    translation[key] = {
      ...(translation[key] || {}),
      [locale]: data[key],
    }
  })
  return translation
}
```

`addLocale` might be a utility method that I include in a future release, but this should suffice for you.

Hope this helps!

**Comment by nelsieborja** [comment]
Got it! Thanks so much this really helped me a lot! :)
